export enum DocumentType {
    Undefined = "",
    UsPassport = "US passport",
    ResidentAlienCard = "Resident alien card",
    AlienRegistrationReceipt = "Alien registration receipt",
    ForeignPassport = "Foreign passport",
    EmploymentAuthorizationDocument = "Employment authorization document",
    FormI94 = "Form I-94/I-94A",
    MicronesiaPassport = "Micronesia passport",
    DriversLicense = "Drivers license",
    IdCard = "ID card",
    SchoolIdCard = "School ID card",
    VoterRegistrationCard = "Voter registration card",
    UsMilitaryCard = "US military card",
    UsCoastGuard = "US Coast Guard/mariner card",
    TribalDocument = "Native American tribal document",
    CanadianDriversLicense = "Canadian drivers license",
    SchoolRecordCard = "School record/report card",
    HospitalRecord = "Clinic/doctor/hospital record",
    DayCareRecord = "Day-care record",
    SocialSecurityCard = "Social security card",
    BirthCertificate = "Birth certificate",
    BirthCertificateCopy = "Certified birth certificate copy",
    UsCitizenIdCard = "US citizen ID card",
    DhsEmploymentAuthorization = "DHS employment authorization"
}
